### ISSUE TITLE
Cross-compiler (gcc) issue with SFINAE in Vector cross product.

### ISSUE THREAD

**Issue by rkernan** [kernan/vmath#5]
Project will compile in clang (v3.2) but not with gcc (v4.8.2). I wouldn't consider this an issue except I'm not sure which compiler is wrong (gcc for rejecting it or clang for accepting it), so I don't know how Visual Studio will react.

The error:

```
In file included from /home/rkernan/workspace/math/inc/math/types.hpp:4:0,
                 from /home/rkernan/workspace/math/test/math/vector2_unit.cpp:8:
/home/rkernan/workspace/math/inc/math/core/vector.hpp: In instantiation of ‘class math::core::Vector<float, 2ul>’:
/home/rkernan/workspace/math/test/math/vector2_unit.cpp:14:16:   required from here
/home/rkernan/workspace/math/inc/math/core/vector.hpp:180:22: error: no type named ‘type’ in ‘struct std::enable_if<false, float>’
  static Vector<T, N> cross(const Vector<T, N>&, const Vector<T, N>&);
                      ^
make[2]: *** [CMakeFiles/math_tester.dir/test/math/vector2_unit.cpp.o] Error 1
make[1]: *** [CMakeFiles/math_tester.dir/all] Error 2
make: *** [all] Error 2

```
